version: 2
updates:
  # Keep npm dependencies updated
  - package-ecosystem: "npm"
    directory: "/"                # Location of package.json
    schedule:
      interval: "weekly"          # Options: "daily", "weekly", "monthly"
    open-pull-requests-limit: 5   # Prevent too many PRs at once
    commit-message:
      prefix: "chore"
      include: "scope"
    labels:
      - "dependencies"
      - "automated"
    reviewers:
      - "Fadil369"                # Add your username or teammates
    assignees:
      - "Fadil369"
    ignore:
      - dependency-name: "some-large-lib"
        versions: [">=5.0.0"]

  # Keep GitHub Actions up to date
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "fix"
      include: "scope"
    labels:
      - "ci"
      - "dependencies"
