# Cloudflare Pages Configuration
[build]
  # No build command needed for static site
  command = ""
  
  # Output directory (current directory since it's a static site)
  publish = "."
  
  # Environment variables
  [build.environment]
    NODE_VERSION = "18"
    NPM_VERSION = "9"

# Custom redirects
[[redirects]]
  from = "/index.html"
  to = "/"
  status = 301

[[redirects]]
  from = "/home"
  to = "/"
  status = 301

[[redirects]]
  from = "/about"
  to = "/"
  status = 301

# SPA fallback for any unmatched routes
[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200

# Headers configuration (supplements _headers file)
[[headers]]
  for = "/*"
  [headers.values]
    X-Robots-Tag = "index, follow"
    X-Content-Type-Options = "nosniff"
    
[[headers]]
  for = "/manifest.json"
  [headers.values]
    Content-Type = "application/manifest+json"
    Cache-Control = "public, max-age=86400"

[[headers]]
  for = "/sw.js"
  [headers.values]
    Content-Type = "application/javascript"
    Cache-Control = "no-cache"

# Custom error pages
[functions]
  directory = "functions"