version: '3.8'

services:
  graphql-api:
    build: .
    ports:
      - "4000:4000"
    environment:
      - NODE_ENV=development
      - PORT=4000
    volumes:
      # Mount source code for development
      - ./server:/app/server
      - ./package.json:/app/package.json
    restart: unless-stopped
    healthcheck:
      test: ["CMD-SHELL", "curl -f http://localhost:4000/graphql?query={__typename} || exit 1"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 30s

  web:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./:/usr/share/nginx/html:ro
      - ./nginx.conf:/etc/nginx/conf.d/default.conf:ro
    depends_on:
      - graphql-api
    restart: unless-stopped

networks:
  default:
    name: dr-fadil-healthcare